% this code is used to retrain the model with more epochs

load('detector.mat');

options = trainingOptions('sgdm', ...
      'MiniBatchSize', 1, ...
      'InitialLearnRate', 1e-3, ...
      'MaxEpochs', 50, ...
      'VerboseFrequency', 20, ...
      'CheckpointPath', tempdir);
  
  detector = trainFasterRCNNObjectDetector(trainingData, detector, options, ...
        'NegativeOverlapRange',[0 0.5], ...
        'PositiveOverlapRange',[0.5 1]);
    
   % save the detector 